import { AWSService } from "./types";

export const AWS_SERVICES: AWSService[] = [
  {
    id: "vpc",
    name: "VPC",
    description: "Virtual Private Cloud - Isolated network environment for your AWS resources",
    icon: "Network",
    category: "networking",
    dependencies: [],
    configFields: [
      {
        name: "cidr_block",
        label: "CIDR Block",
        type: "text",
        default: "10.0.0.0/16",
        required: true,
        description: "The IPv4 CIDR block for the VPC",
      },
      {
        name: "enable_dns",
        label: "Enable DNS Support",
        type: "boolean",
        default: true,
        description: "Enable DNS resolution in the VPC",
      },
      {
        name: "public_subnets",
        label: "Number of Public Subnets",
        type: "select",
        default: "2",
        options: [
          { label: "1", value: "1" },
          { label: "2", value: "2" },
          { label: "3", value: "3" },
        ],
      },
      {
        name: "private_subnets",
        label: "Number of Private Subnets",
        type: "select",
        default: "2",
        options: [
          { label: "0", value: "0" },
          { label: "1", value: "1" },
          { label: "2", value: "2" },
          { label: "3", value: "3" },
        ],
      },
      {
        name: "enable_nat",
        label: "Enable NAT Gateway",
        type: "boolean",
        default: false,
        description: "Enable NAT gateway for private subnets",
      },
    ],
  },
  {
    id: "ec2",
    name: "EC2",
    description: "Elastic Compute Cloud - Scalable virtual servers in the cloud",
    icon: "Server",
    category: "compute",
    dependencies: ["vpc"],
    configFields: [
      {
        name: "instance_type",
        label: "Instance Type",
        type: "select",
        default: "t3.micro",
        options: [
          { label: "t3.micro", value: "t3.micro" },
          { label: "t3.small", value: "t3.small" },
          { label: "t3.medium", value: "t3.medium" },
          { label: "t3.large", value: "t3.large" },
          { label: "m5.large", value: "m5.large" },
          { label: "m5.xlarge", value: "m5.xlarge" },
          { label: "c5.large", value: "c5.large" },
          { label: "c5.xlarge", value: "c5.xlarge" },
        ],
        required: true,
      },
      {
        name: "instance_count",
        label: "Number of Instances",
        type: "number",
        default: 1,
        required: true,
        description: "Number of EC2 instances to launch",
      },
      {
        name: "ami_type",
        label: "AMI Type",
        type: "select",
        default: "amazon-linux-2023",
        options: [
          { label: "Amazon Linux 2023", value: "amazon-linux-2023" },
          { label: "Ubuntu 22.04", value: "ubuntu-22.04" },
          { label: "Ubuntu 24.04", value: "ubuntu-24.04" },
          { label: "Windows Server 2022", value: "windows-2022" },
        ],
      },
      {
        name: "root_volume_size",
        label: "Root Volume Size (GB)",
        type: "number",
        default: 20,
        description: "Size of the root EBS volume in GB",
      },
      {
        name: "enable_public_ip",
        label: "Assign Public IP",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "s3",
    name: "S3",
    description: "Simple Storage Service - Scalable object storage for any data",
    icon: "HardDrive",
    category: "storage",
    dependencies: [],
    configFields: [
      {
        name: "bucket_name",
        label: "Bucket Name Suffix",
        type: "text",
        default: "data",
        required: true,
        description: "Suffix for the S3 bucket name",
      },
      {
        name: "versioning",
        label: "Enable Versioning",
        type: "boolean",
        default: true,
        description: "Enable versioning for the bucket",
      },
      {
        name: "encryption",
        label: "Encryption",
        type: "select",
        default: "AES256",
        options: [
          { label: "AES-256", value: "AES256" },
          { label: "AWS KMS", value: "aws:kms" },
          { label: "None", value: "none" },
        ],
      },
      {
        name: "block_public_access",
        label: "Block Public Access",
        type: "boolean",
        default: true,
        description: "Block all public access to the bucket",
      },
    ],
  },
  {
    id: "rds",
    name: "RDS",
    description: "Relational Database Service - Managed relational databases",
    icon: "Database",
    category: "database",
    dependencies: ["vpc"],
    configFields: [
      {
        name: "engine",
        label: "Database Engine",
        type: "select",
        default: "postgres",
        options: [
          { label: "PostgreSQL", value: "postgres" },
          { label: "MySQL", value: "mysql" },
          { label: "MariaDB", value: "mariadb" },
          { label: "SQL Server", value: "sqlserver" },
        ],
        required: true,
      },
      {
        name: "engine_version",
        label: "Engine Version",
        type: "select",
        default: "16",
        options: [
          { label: "PostgreSQL 16", value: "16" },
          { label: "PostgreSQL 15", value: "15" },
          { label: "MySQL 8.0", value: "8.0" },
          { label: "MariaDB 10.11", value: "10.11" },
        ],
      },
      {
        name: "instance_class",
        label: "Instance Class",
        type: "select",
        default: "db.t3.micro",
        options: [
          { label: "db.t3.micro", value: "db.t3.micro" },
          { label: "db.t3.small", value: "db.t3.small" },
          { label: "db.t3.medium", value: "db.t3.medium" },
          { label: "db.r5.large", value: "db.r5.large" },
          { label: "db.r5.xlarge", value: "db.r5.xlarge" },
        ],
        required: true,
      },
      {
        name: "allocated_storage",
        label: "Storage (GB)",
        type: "number",
        default: 20,
        required: true,
      },
      {
        name: "multi_az",
        label: "Multi-AZ Deployment",
        type: "boolean",
        default: false,
        description: "Enable Multi-AZ for high availability",
      },
      {
        name: "backup_retention",
        label: "Backup Retention (Days)",
        type: "number",
        default: 7,
      },
    ],
  },
  {
    id: "alb",
    name: "Application Load Balancer",
    description: "Distribute incoming traffic across multiple targets",
    icon: "GitFork",
    category: "networking",
    dependencies: ["vpc"],
    configFields: [
      {
        name: "internal",
        label: "Internal Load Balancer",
        type: "boolean",
        default: false,
        description: "Make load balancer internal (not internet-facing)",
      },
      {
        name: "health_check_path",
        label: "Health Check Path",
        type: "text",
        default: "/",
        description: "Path for target group health checks",
      },
      {
        name: "listener_port",
        label: "Listener Port",
        type: "select",
        default: "80",
        options: [
          { label: "80 (HTTP)", value: "80" },
          { label: "443 (HTTPS)", value: "443" },
        ],
      },
      {
        name: "target_port",
        label: "Target Port",
        type: "number",
        default: 80,
        description: "Port on which targets receive traffic",
      },
    ],
  },
  {
    id: "iam",
    name: "IAM",
    description: "Identity and Access Management - Manage access to AWS resources",
    icon: "Shield",
    category: "security",
    dependencies: [],
    configFields: [
      {
        name: "create_admin_role",
        label: "Create Admin Role",
        type: "boolean",
        default: false,
        description: "Create an IAM role with admin access",
      },
      {
        name: "create_ec2_role",
        label: "Create EC2 Instance Role",
        type: "boolean",
        default: true,
        description: "Create an IAM role for EC2 instances",
      },
      {
        name: "create_s3_policy",
        label: "Create S3 Access Policy",
        type: "boolean",
        default: false,
        description: "Create a policy for S3 bucket access",
      },
      {
        name: "create_rds_policy",
        label: "Create RDS Access Policy",
        type: "boolean",
        default: false,
        description: "Create a policy for RDS access",
      },
    ],
  },
  {
    id: "route53",
    name: "Route 53",
    description: "Domain Name System (DNS) web service - Reliable and cost-effective way to route visitors",
    icon: "Globe",
    category: "networking",
    dependencies: [],
    configFields: [
      {
        name: "domain_name",
        label: "Domain Name",
        type: "text",
        default: "example.com",
        required: true,
        description: "Your registered domain name",
      },
      {
        name: "create_hosted_zone",
        label: "Create Hosted Zone",
        type: "boolean",
        default: true,
        description: "Create a new Route 53 hosted zone",
      },
      {
        name: "create_records",
        label: "Create DNS Records",
        type: "boolean",
        default: true,
        description: "Create A, CNAME, MX, SPF, and DMARC records",
      },
      {
        name: "subdomain",
        label: "Application Subdomain",
        type: "text",
        default: "app",
        description: "Subdomain for the application (e.g., app.example.com)",
      },
      {
        name: "health_checks",
        label: "Enable Health Checks",
        type: "boolean",
        default: false,
        description: "Create Route 53 health checks for monitoring",
      },
      {
        name: "health_check_path",
        label: "Health Check Path",
        type: "text",
        default: "/health",
        description: "Path for health check endpoint",
      },
    ],
  },
  {
    id: "efs",
    name: "EFS",
    description: "Elastic File System - Scalable file storage for use with EC2 instances",
    icon: "HardDrive",
    category: "storage",
    dependencies: ["vpc"],
    configFields: [
      {
        name: "performance_mode",
        label: "Performance Mode",
        type: "select",
        default: "generalPurpose",
        options: [
          { label: "General Purpose", value: "generalPurpose" },
          { label: "Max I/O", value: "maxIO" },
        ],
        description: "File system performance mode",
      },
      {
        name: "throughput_mode",
        label: "Throughput Mode",
        type: "select",
        default: "bursting",
        options: [
          { label: "Bursting", value: "bursting" },
          { label: "Provisioned", value: "provisioned" },
        ],
        description: "File system throughput mode",
      },
      {
        name: "encrypted",
        label: "Enable Encryption",
        type: "boolean",
        default: true,
        description: "Encrypt data at rest",
      },
      {
        name: "mount_targets",
        label: "Number of Mount Targets",
        type: "select",
        default: "2",
        options: [
          { label: "1", value: "1" },
          { label: "2", value: "2" },
          { label: "3", value: "3" },
          { label: "4", value: "4" },
        ],
        description: "Number of mount targets (one per subnet)",
      },
      {
        name: "enable_backup",
        label: "Enable Backup",
        type: "boolean",
        default: false,
        description: "Enable automatic daily backups",
      },
      {
        name: "enable_monitoring",
        label: "Enable Monitoring",
        type: "boolean",
        default: false,
        description: "Create CloudWatch alarms for monitoring",
      },
    ],
  },
  {
    id: "sqs",
    name: "SQS",
    description: "Simple Queue Service - Fully managed message queuing service",
    icon: "MessageSquare",
    category: "messaging",
    dependencies: [],
    configFields: [
      {
        name: "queue_name",
        label: "Queue Name",
        type: "text",
        default: "messages",
        required: true,
        description: "Name for the SQS queue",
      },
      {
        name: "queue_type",
        label: "Queue Type",
        type: "select",
        default: "standard",
        options: [
          { label: "Standard Queue", value: "standard" },
          { label: "FIFO Queue", value: "fifo" },
        ],
        required: true,
        description: "Type of queue (Standard or FIFO)",
      },
      {
        name: "visibility_timeout",
        label: "Visibility Timeout (seconds)",
        type: "number",
        default: 30,
        description: "Time a message is invisible after being read",
      },
      {
        name: "message_retention_period",
        label: "Message Retention (days)",
        type: "number",
        default: 4,
        description: "How long to retain messages (1-14 days)",
      },
      {
        name: "dead_letter_queue",
        label: "Enable Dead Letter Queue",
        type: "boolean",
        default: false,
        description: "Create a dead letter queue for failed messages",
      },
      {
        name: "enable_encryption",
        label: "Enable Encryption",
        type: "boolean",
        default: true,
        description: "Enable server-side encryption",
      },
      {
        name: "enable_monitoring",
        label: "Enable Monitoring",
        type: "boolean",
        default: false,
        description: "Create CloudWatch alarms for monitoring",
      },
    ],
  },
  {
    id: "sns",
    name: "SNS",
    description: "Simple Notification Service - Fully managed pub/sub messaging",
    icon: "Bell",
    category: "messaging",
    dependencies: [],
    configFields: [
      {
        name: "topic_name",
        label: "Topic Name",
        type: "text",
        default: "notifications",
        required: true,
        description: "Name for the SNS topic",
      },
      {
        name: "display_name",
        label: "Display Name",
        type: "text",
        default: "My Notifications",
        description: "Display name for email notifications",
      },
      {
        name: "topic_type",
        label: "Topic Type",
        type: "select",
        default: "standard",
        options: [
          { label: "Standard", value: "standard" },
          { label: "FIFO", value: "fifo" },
        ],
        required: true,
        description: "Type of topic (Standard or FIFO)",
      },
      {
        name: "enable_encryption",
        label: "Enable Encryption",
        type: "boolean",
        default: true,
        description: "Enable server-side encryption",
      },
      {
        name: "enable_monitoring",
        label: "Enable Monitoring",
        type: "boolean",
        default: false,
        description: "Create CloudWatch alarms for monitoring",
      },
      {
        name: "email_subscriptions",
        label: "Email Subscriptions",
        type: "text",
        default: "",
        description: "Comma-separated email addresses for notifications",
      },
    ],
  },
  {
    id: "lambda",
    name: "Lambda",
    description: "Serverless compute service - Run code without provisioning servers",
    icon: "Zap",
    category: "compute",
    dependencies: ["iam"],
    configFields: [
      {
        name: "function_name",
        label: "Function Name",
        type: "text",
        default: "my-function",
        required: true,
        description: "Name for the Lambda function",
      },
      {
        name: "runtime",
        label: "Runtime",
        type: "select",
        default: "python3.11",
        options: [
          { label: "Python 3.11", value: "python3.11" },
          { label: "Python 3.10", value: "python3.10" },
          { label: "Node.js 20.x", value: "nodejs20.x" },
          { label: "Node.js 18.x", value: "nodejs18.x" },
          { label: "Java 21", value: "java21" },
          { label: "Go 1.x", value: "go1.x" },
          { label: "Dotnet 8", value: "dotnet8" },
        ],
        required: true,
      },
      {
        name: "handler",
        label: "Handler",
        type: "text",
        default: "index.lambda_handler",
        required: true,
        description: "Function handler (e.g., index.lambda_handler)",
      },
      {
        name: "memory_size",
        label: "Memory Size (MB)",
        type: "select",
        default: "128",
        options: [
          { label: "128 MB", value: "128" },
          { label: "256 MB", value: "256" },
          { label: "512 MB", value: "512" },
          { label: "1024 MB", value: "1024" },
          { label: "2048 MB", value: "2048" },
        ],
        required: true,
      },
      {
        name: "timeout",
        label: "Timeout (seconds)",
        type: "number",
        default: 30,
        description: "Function execution timeout (1-900 seconds)",
      },
      {
        name: "enable_vpc",
        label: "Enable VPC Access",
        type: "boolean",
        default: false,
        description: "Deploy Lambda in VPC for private resource access",
      },
      {
        name: "enable_monitoring",
        label: "Enable Monitoring",
        type: "boolean",
        default: false,
        description: "Create CloudWatch alarms for monitoring",
      },
      {
        name: "enable_tracing",
        label: "Enable X-Ray Tracing",
        type: "boolean",
        default: false,
        description: "Enable AWS X-Ray tracing",
      },
      {
        name: "environment_variables",
        label: "Environment Variables",
        type: "text",
        default: "",
        description: "Key-value pairs (format: KEY1=value1,KEY2=value2)",
      },
    ],
  },
  {
    id: "elasticache",
    name: "ElastiCache",
    description: "In-memory caching service for improved performance",
    icon: "Database",
    category: "database",
    dependencies: ["vpc"],
    configFields: [
      {
        name: "engine",
        label: "Cache Engine",
        type: "select",
        default: "redis",
        options: [
          { label: "Redis", value: "redis" },
          { label: "Memcached", value: "memcached" },
        ],
        required: true,
      },
      {
        name: "node_type",
        label: "Node Type",
        type: "select",
        default: "cache.t3.micro",
        options: [
          { label: "cache.t3.micro", value: "cache.t3.micro" },
          { label: "cache.t3.small", value: "cache.t3.small" },
          { label: "cache.t3.medium", value: "cache.t3.medium" },
          { label: "cache.r5.large", value: "cache.r5.large" },
        ],
        required: true,
      },
      {
        name: "num_cache_nodes",
        label: "Number of Cache Nodes",
        type: "select",
        default: "1",
        options: [
          { label: "1", value: "1" },
          { label: "2", value: "2" },
          { label: "3", value: "3" },
          { label: "4", value: "4" },
        ],
        description: "Number of cache nodes in the cluster",
      },
      {
        name: "automatic_failover",
        label: "Automatic Failover",
        type: "boolean",
        default: false,
        description: "Enable automatic failover for Redis (requires 2+ nodes)",
      },
      {
        name: "encrypted",
        label: "Enable Encryption",
        type: "boolean",
        default: true,
        description: "Enable encryption at rest and in transit",
      },
      {
        name: "enable_monitoring",
        label: "Enable Monitoring",
        type: "boolean",
        default: false,
        description: "Create CloudWatch alarms for monitoring",
      },
    ],
  },
  {
    id: "api-gateway",
    name: "API Gateway",
    description: "Build, deploy, and manage APIs at any scale",
    icon: "Globe",
    category: "networking",
    dependencies: ["iam"],
    configFields: [
      {
        name: "api_type",
        label: "API Type",
        type: "select",
        default: "rest",
        options: [
          { label: "REST API", value: "rest" },
          { label: "HTTP API", value: "http" },
        ],
        required: true,
      },
      {
        name: "stage_name",
        label: "Stage Name",
        type: "text",
        default: "prod",
        required: true,
        description: "Deployment stage name",
      },
      {
        name: "enable_cors",
        label: "Enable CORS",
        type: "boolean",
        default: true,
        description: "Enable Cross-Origin Resource Sharing",
      },
      {
        name: "enable_logging",
        label: "Enable Logging",
        type: "boolean",
        default: true,
        description: "Enable access logging to CloudWatch",
      },
      {
        name: "enable_throttling",
        label: "Enable Throttling",
        type: "boolean",
        default: false,
        description: "Enable rate limiting",
      },
      {
        name: "enable_waf",
        label: "Enable WAF",
        type: "boolean",
        default: false,
        description: "Enable AWS WAF protection",
      },
      {
        name: "enable_monitoring",
        label: "Enable Monitoring",
        type: "boolean",
        default: false,
        description: "Create CloudWatch alarms for monitoring",
      },
    ],
  },
  {
    id: "cloudwatch",
    name: "CloudWatch",
    description: "Monitoring and observability service for AWS resources",
    icon: "Activity",
    category: "management",
    dependencies: ["iam"],
    configFields: [
      {
        name: "enable_log_group",
        label: "Create Log Groups",
        type: "boolean",
        default: true,
        description: "Create CloudWatch Log Groups for services",
      },
      {
        name: "log_retention_days",
        label: "Log Retention (days)",
        type: "select",
        default: "14",
        options: [
          { label: "1 day", value: "1" },
          { label: "3 days", value: "3" },
          { label: "7 days", value: "7" },
          { label: "14 days", value: "14" },
          { label: "30 days", value: "30" },
          { label: "60 days", value: "60" },
          { label: "90 days", value: "90" },
        ],
        description: "Default log retention period",
      },
      {
        name: "enable_alarms",
        label: "Create CloudWatch Alarms",
        type: "boolean",
        default: false,
        description: "Create basic monitoring alarms for resources",
      },
      {
        name: "enable_dashboard",
        label: "Create Dashboard",
        type: "boolean",
        default: false,
        description: "Create a CloudWatch Dashboard with metrics",
      },
      {
        name: "enable_metric_filters",
        label: "Enable Metric Filters",
        type: "boolean",
        default: false,
        description: "Create metric filters for log analysis",
      },
    ],
  },
  {
    id: "lambda",
    name: "Lambda",
    description: "Serverless compute service - Run code without provisioning servers",
    icon: "Zap",
    category: "compute",
    dependencies: ["iam"],
    configFields: [
      {
        name: "runtime",
        label: "Runtime",
        type: "select",
        default: "python3.11",
        options: [
          { label: "Python 3.11", value: "python3.11" },
          { label: "Python 3.10", value: "python3.10" },
          { label: "Node.js 20.x", value: "nodejs20.x" },
          { label: "Node.js 18.x", value: "nodejs18.x" },
          { label: "Java 21", value: "java21" },
          { label: "Go 1.x", value: "go1.x" },
          { label: "Dotnet 8", value: "dotnet8" },
        ],
        required: true,
      },
      {
        name: "memory_size",
        label: "Memory Size (MB)",
        type: "select",
        default: "128",
        options: [
          { label: "128 MB", value: "128" },
          { label: "256 MB", value: "256" },
          { label: "512 MB", value: "512" },
          { label: "1024 MB", value: "1024" },
          { label: "2048 MB", value: "2048" },
        ],
        required: true,
      },
      {
        name: "timeout",
        label: "Timeout (seconds)",
        type: "number",
        default: 30,
        description: "Function execution timeout in seconds",
      },
      {
        name: "environment_variables",
        label: "Environment Variables",
        type: "text",
        default: "",
        description: "Key-value pairs (format: KEY1=value1,KEY2=value2)",
      },
    ],
  },
  {
    id: "cloudfront",
    name: "CloudFront",
    description: "Content Delivery Network - Speed up content delivery with low latency",
    icon: "Cloud",
    category: "networking",
    dependencies: ["s3"],
    configFields: [
      {
        name: "price_class",
        label: "Price Class",
        type: "select",
        default: "PriceClass_100",
        options: [
          { label: "Price Class 100 (US, Canada, Europe)", value: "PriceClass_100" },
          { label: "Price Class 200 (All except South America)", value: "PriceClass_200" },
          { label: "Price Class All (All locations)", value: "PriceClass_All" },
        ],
        required: true,
      },
      {
        name: "default_ttl",
        label: "Default TTL (seconds)",
        type: "number",
        default: 86400,
        description: "Default cache duration",
      },
      {
        name: "enable_compress",
        label: "Enable Compression",
        type: "boolean",
        default: true,
        description: "Compress files automatically",
      },
      {
        name: "enable_https_only",
        label: "HTTPS Only",
        type: "boolean",
        default: true,
        description: "Redirect HTTP to HTTPS",
      },
    ],
  },
  {
    id: "ecs",
    name: "ECS",
    description: "Elastic Container Service - Run and manage Docker containers",
    icon: "Package",
    category: "compute",
    dependencies: ["vpc", "iam"],
    configFields: [
      {
        name: "launch_type",
        label: "Launch Type",
        type: "select",
        default: "FARGATE",
        options: [
          { label: "Fargate", value: "FARGATE" },
          { label: "EC2", value: "EC2" },
        ],
        required: true,
      },
      {
        name: "task_cpu",
        label: "Task CPU (vCPU)",
        type: "select",
        default: "256",
        options: [
          { label: "0.25 vCPU", value: "256" },
          { label: "0.5 vCPU", value: "512" },
          { label: "1 vCPU", value: "1024" },
          { label: "2 vCPU", value: "2048" },
          { label: "4 vCPU", value: "4096" },
        ],
        required: true,
      },
      {
        name: "task_memory",
        label: "Task Memory (MB)",
        type: "select",
        default: "512",
        options: [
          { label: "0.5 GB", value: "512" },
          { label: "1 GB", value: "1024" },
          { label: "2 GB", value: "2048" },
          { label: "4 GB", value: "4096" },
          { label: "8 GB", value: "8192" },
        ],
        required: true,
      },
      {
        name: "desired_count",
        label: "Desired Count",
        type: "number",
        default: 1,
        description: "Number of tasks to run",
      },
      {
        name: "enable_load_balancing",
        label: "Enable Load Balancing",
        type: "boolean",
        default: false,
        description: "Attach to Application Load Balancer",
      },
    ],
  },
  {
    id: "eks",
    name: "EKS",
    description: "Elastic Kubernetes Service - Managed Kubernetes service",
    icon: "Package",
    category: "compute",
    dependencies: ["vpc", "iam"],
    configFields: [
      {
        name: "kubernetes_version",
        label: "Kubernetes Version",
        type: "select",
        default: "1.29",
        options: [
          { label: "1.29", value: "1.29" },
          { label: "1.28", value: "1.28" },
          { label: "1.27", value: "1.27" },
          { label: "1.26", value: "1.26" },
        ],
        required: true,
      },
      {
        name: "node_group_instance_type",
        label: "Node Instance Type",
        type: "select",
        default: "t3.medium",
        options: [
          { label: "t3.medium", value: "t3.medium" },
          { label: "t3.large", value: "t3.large" },
          { label: "t3.xlarge", value: "t3.xlarge" },
          { label: "m5.large", value: "m5.large" },
          { label: "m5.xlarge", value: "m5.xlarge" },
        ],
        required: true,
      },
      {
        name: "node_group_desired_size",
        label: "Node Group Desired Size",
        type: "number",
        default: 2,
        description: "Desired number of worker nodes",
      },
      {
        name: "node_group_min_size",
        label: "Node Group Minimum Size",
        type: "number",
        default: 1,
      },
      {
        name: "node_group_max_size",
        label: "Node Group Maximum Size",
        type: "number",
        default: 4,
      },
    ],
  },
  {
    id: "dynamodb",
    name: "DynamoDB",
    description: "Fast and flexible NoSQL database service",
    icon: "Database",
    category: "database",
    dependencies: ["iam"],
    configFields: [
      {
        name: "table_name",
        label: "Table Name",
        type: "text",
        default: "items",
        required: true,
      },
      {
        name: "billing_mode",
        label: "Billing Mode",
        type: "select",
        default: "PAY_PER_REQUEST",
        options: [
          { label: "Pay Per Request", value: "PAY_PER_REQUEST" },
          { label: "Provisioned", value: "PROVISIONED" },
        ],
        required: true,
      },
      {
        name: "read_capacity",
        label: "Read Capacity Units",
        type: "number",
        default: 5,
        description: "Provisioned read capacity (only for Provisioned mode)",
      },
      {
        name: "write_capacity",
        label: "Write Capacity Units",
        type: "number",
        default: 5,
        description: "Provisioned write capacity (only for Provisioned mode)",
      },
      {
        name: "enable_streams",
        label: "Enable Streams",
        type: "boolean",
        default: false,
        description: "Enable DynamoDB Streams",
      },
      {
        name: "enable_encryption",
        label: "Enable Encryption",
        type: "boolean",
        default: true,
        description: "Enable at-rest encryption",
      },
    ],
  },
  {
    id: "elasticache",
    name: "ElastiCache",
    description: "In-memory caching service for improved performance",
    icon: "Database",
    category: "database",
    dependencies: ["vpc"],
    configFields: [
      {
        name: "engine",
        label: "Cache Engine",
        type: "select",
        default: "redis",
        options: [
          { label: "Redis", value: "redis" },
          { label: "Memcached", value: "memcached" },
        ],
        required: true,
      },
      {
        name: "node_type",
        label: "Node Type",
        type: "select",
        default: "cache.t3.micro",
        options: [
          { label: "cache.t3.micro", value: "cache.t3.micro" },
          { label: "cache.t3.small", value: "cache.t3.small" },
          { label: "cache.t3.medium", value: "cache.t3.medium" },
          { label: "cache.m5.large", value: "cache.m5.large" },
          { label: "cache.m5.xlarge", value: "cache.m5.xlarge" },
        ],
        required: true,
      },
      {
        name: "num_cache_nodes",
        label: "Number of Cache Nodes",
        type: "number",
        default: 1,
        description: "Number of cache nodes in the cluster",
      },
      {
        name: "automatic_failover",
        label: "Automatic Failover",
        type: "boolean",
        default: false,
        description: "Enable automatic failover for Redis",
      },
      {
        name: "multi_az",
        label: "Multi-AZ",
        type: "boolean",
        default: false,
        description: "Deploy nodes in multiple AZs",
      },
    ],
  },
  {
    id: "sqs",
    name: "SQS",
    description: "Simple Queue Service - Fully managed message queuing service",
    icon: "MessageSquare",
    category: "messaging",
    dependencies: ["iam"],
    configFields: [
      {
        name: "queue_name",
        label: "Queue Name",
        type: "text",
        default: "messages",
        required: true,
      },
      {
        name: "queue_type",
        label: "Queue Type",
        type: "select",
        default: "standard",
        options: [
          { label: "Standard Queue", value: "standard" },
          { label: "FIFO Queue", value: "fifo" },
        ],
        required: true,
      },
      {
        name: "visibility_timeout",
        label: "Visibility Timeout (seconds)",
        type: "number",
        default: 30,
        description: "Time a message is invisible after being read",
      },
      {
        name: "message_retention_period",
        label: "Message Retention (days)",
        type: "number",
        default: 4,
        description: "How long to retain messages",
      },
      {
        name: "dead_letter_queue",
        label: "Enable Dead Letter Queue",
        type: "boolean",
        default: false,
        description: "Create a dead letter queue for failed messages",
      },
    ],
  },
  {
    id: "sns",
    name: "SNS",
    description: "Simple Notification Service - Fully managed pub/sub messaging",
    icon: "Bell",
    category: "messaging",
    dependencies: ["iam"],
    configFields: [
      {
        name: "topic_name",
        label: "Topic Name",
        type: "text",
        default: "notifications",
        required: true,
      },
      {
        name: "display_name",
        label: "Display Name",
        type: "text",
        default: "My Notifications",
        description: "Display name for email notifications",
      },
      {
        name: "type",
        label: "Topic Type",
        type: "select",
        default: "standard",
        options: [
          { label: "Standard", value: "standard" },
          { label: "FIFO", value: "fifo" },
        ],
        required: true,
      },
      {
        name: "delivery_policy",
        label: "Enable Delivery Policy",
        type: "boolean",
        default: false,
        description: "Configure retry policies for failed deliveries",
      },
    ],
  },
  {
    id: "cloudwatch",
    name: "CloudWatch",
    description: "Monitoring and observability service for AWS resources",
    icon: "Activity",
    category: "management",
    dependencies: ["iam"],
    configFields: [
      {
        name: "enable_log_group",
        label: "Create Log Group",
        type: "boolean",
        default: true,
        description: "Create a CloudWatch Log Group",
      },
      {
        name: "log_retention_days",
        label: "Log Retention (days)",
        type: "select",
        default: "14",
        options: [
          { label: "1 day", value: "1" },
          { label: "3 days", value: "3" },
          { label: "7 days", value: "7" },
          { label: "14 days", value: "14" },
          { label: "30 days", value: "30" },
          { label: "60 days", value: "60" },
          { label: "90 days", value: "90" },
        ],
      },
      {
        name: "enable_alarm",
        label: "Create CloudWatch Alarms",
        type: "boolean",
        default: false,
        description: "Create basic monitoring alarms",
      },
      {
        name: "enable_dashboard",
        label: "Create Dashboard",
        type: "boolean",
        default: false,
        description: "Create a CloudWatch Dashboard",
      },
    ],
  },
];

export const AWS_REGIONS = [
  { label: "US East (N. Virginia)", value: "us-east-1" },
  { label: "US East (Ohio)", value: "us-east-2" },
  { label: "US West (N. California)", value: "us-west-1" },
  { label: "US West (Oregon)", value: "us-west-2" },
  { label: "EU (Ireland)", value: "eu-west-1" },
  { label: "EU (London)", value: "eu-west-2" },
  { label: "EU (Frankfurt)", value: "eu-central-1" },
  { label: "Asia Pacific (Mumbai)", value: "ap-south-1" },
  { label: "Asia Pacific (Singapore)", value: "ap-southeast-1" },
  { label: "Asia Pacific (Sydney)", value: "ap-southeast-2" },
  { label: "Asia Pacific (Tokyo)", value: "ap-northeast-1" },
  { label: "Canada (Central)", value: "ca-central-1" },
  { label: "South America (São Paulo)", value: "sa-east-1" },
];

export const SERVICE_CATEGORIES = [
  { id: "networking" as const, label: "Networking", icon: "Network" },
  { id: "compute" as const, label: "Compute", icon: "Server" },
  { id: "storage" as const, label: "Storage", icon: "HardDrive" },
  { id: "database" as const, label: "Database", icon: "Database" },
  { id: "security" as const, label: "Security", icon: "Shield" },
  { id: "messaging" as const, label: "Messaging", icon: "MessageSquare" },
  { id: "management" as const, label: "Management", icon: "Activity" },
];

export function getServiceById(id: string): AWSService | undefined {
  return AWS_SERVICES.find((s) => s.id === id);
}

export function getServiceDependencies(serviceId: string): string[] {
  const service = getServiceById(serviceId);
  if (!service) return [];

  const allDeps: Set<string> = new Set();

  function resolveDeps(sid: string) {
    const s = getServiceById(sid);
    if (!s) return;
    for (const dep of s.dependencies) {
      if (!allDeps.has(dep)) {
        allDeps.add(dep);
        resolveDeps(dep);
      }
    }
  }

  resolveDeps(serviceId);
  return Array.from(allDeps);
}
