import type { GeneratedFile, OutputFormat } from "./types";

export function buildReadmeContent(options: {
  projectName: string;
  environment: string;
  region: string;
  outputFormat: OutputFormat;
  services: string[];
}): string {
  const { projectName, environment, region, outputFormat, services } = options;
  const deploySteps =
    outputFormat === "terraform"
      ? ["terraform init", "terraform plan", "terraform apply"]
      : outputFormat === "cloudformation"
      ? [
          `aws cloudformation deploy --template-file template.json --stack-name ${projectName}-stack --capabilities CAPABILITY_IAM`,
        ]
      : ["npm install", "npx cdk synth", "npx cdk deploy"];

  return `# ${projectName}

Generated by [AWS Infra Generator](https://github.com/NotHarshhaa/aws-infra-generator).

## Overview

- **Environment:** ${environment}
- **Region:** ${region}
- **Format:** ${outputFormat}
- **Services:** ${services.join(", ")}

## Deploy

\`\`\`bash
cd ${projectName}
${deploySteps.join("\n")}
\`\`\`

## Files

Review generated templates before applying to your AWS account.
`;
}

export function buildGitignoreContent(outputFormat: OutputFormat): string {
  const lines = [".DS_Store", "*.log", ".env", ".env.local"];

  if (outputFormat === "terraform") {
    lines.push(
      ".terraform/",
      ".terraform.lock.hcl",
      "terraform.tfstate",
      "terraform.tfstate.backup",
      "*.tfvars",
      "crash.log"
    );
  } else if (outputFormat === "cdk") {
    lines.push(
      "node_modules/",
      "cdk.out/",
      "dist/",
      "*.js",
      "!.eslintrc.js",
      "*.d.ts",
      "package-lock.json"
    );
  }

  return `${lines.join("\n")}\n`;
}

export function buildExportFileList(
  files: GeneratedFile[],
  options: {
    includeReadme: boolean;
    includeGitignore: boolean;
    projectName: string;
    environment: string;
    region: string;
    outputFormat: OutputFormat;
    services: string[];
  }
): GeneratedFile[] {
  const exportFiles = [...files];

  if (options.includeReadme) {
    exportFiles.push({
      name: "README.md",
      path: `${options.projectName}/README.md`,
      content: buildReadmeContent({
        projectName: options.projectName,
        environment: options.environment,
        region: options.region,
        outputFormat: options.outputFormat,
        services: options.services,
      }),
      language: "markdown",
    });
  }

  if (options.includeGitignore) {
    exportFiles.push({
      name: ".gitignore",
      path: `${options.projectName}/.gitignore`,
      content: buildGitignoreContent(options.outputFormat),
      language: "text",
    });
  }

  return exportFiles;
}
