"use client";

import { ArrowRight, Github, Sparkles, Terminal } from "lucide-react";
import { useTheme } from "next-themes";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { landingStyles } from "./shared/landing-styles";
import { HERO_STATS } from "./landing-data";
import { cn } from "@/lib/utils";

interface LandingHeroProps {
  onGetStarted: () => void;
}

const HERO_CODE = `# Generated by AWS Infra Generator
terraform {
  required_version = ">= 1.5"
}

resource "aws_vpc" "main" {
  cidr_block = var.vpc_cidr
  tags       = local.common_tags
}`;

export function LandingHero({ onGetStarted }: LandingHeroProps) {
  const { resolvedTheme } = useTheme();
  const [mounted, setMounted] = useState(false);

  useEffect(() => setMounted(true), []);

  const logoSrc =
    mounted && resolvedTheme === "dark" ? "/AWS-Dark.svg" : "/AWS-Light.svg";

  return (
    <section className="relative overflow-hidden px-2 sm:px-0 pt-4 sm:pt-8">
      <div className={landingStyles.heroGlow} />

      <div className="grid gap-8 lg:grid-cols-[1.15fr_0.85fr] lg:items-center lg:gap-10">
        <div className="space-y-5 sm:space-y-6 text-center lg:text-left">
          <div className="flex justify-center lg:justify-start">
            <span className={landingStyles.eyebrow}>
              <Sparkles className="h-3.5 w-3.5" />
              Cloud Architecture Studio 2.0
            </span>
          </div>

          <div className="flex justify-center lg:justify-start">
            <div className="inline-flex items-center justify-center rounded-2xl border border-orange-500/20 bg-card/85 p-3.5 shadow-xs backdrop-blur-xl hover:border-orange-500/35 transition-colors">
              <img
                src={logoSrc}
                alt="AWS Logo"
                className="h-10 w-auto sm:h-12"
                suppressHydrationWarning
              />
            </div>
          </div>

          <h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight leading-[1.12]">
            Design AWS infrastructure.
            <span className="block bg-gradient-to-r from-orange-600 via-amber-500 to-orange-500 bg-clip-text text-transparent">
              Generate IaC in seconds.
            </span>
          </h1>

          <p className="text-sm sm:text-base text-muted-foreground max-w-xl mx-auto lg:mx-0 leading-relaxed font-normal">
            Assemble multi-tier AWS architectures with live dependency resolution, security policy auditing, interactive diagrams, and 1-click Terraform, CloudFormation, and AWS CDK output.
          </p>

          <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-center lg:justify-start gap-2.5 sm:gap-3.5">
            <Button
              size="lg"
              onClick={onGetStarted}
              className={cn("w-full sm:w-auto text-sm gap-2", landingStyles.ctaPrimary)}
              id="get-started"
            >
              <Sparkles className="h-4 w-4" />
              Launch Studio
              <ArrowRight className="h-4 w-4" />
            </Button>
            <a
              href="https://github.com/NotHarshhaa/aws-infra-generator"
              target="_blank"
              rel="noopener noreferrer"
              className="w-full sm:w-auto"
            >
              <Button variant="outline" size="lg" className="w-full sm:w-auto rounded-full text-sm h-10 sm:h-11 px-5 border-border/70 hover:bg-muted/60">
                <Github className="mr-2 h-4 w-4" />
                GitHub Repository
              </Button>
            </a>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5 max-w-xl mx-auto lg:mx-0 pt-2">
            {HERO_STATS.map((stat) => (
              <div key={stat.label} className={cn(landingStyles.statChip, "p-3 rounded-2xl bg-card/60")}>
                <span className={cn(landingStyles.statValue, "text-orange-600 dark:text-orange-400 text-lg sm:text-2xl")}>
                  {stat.value}
                </span>
                <span className={landingStyles.statLabel}>{stat.label}</span>
              </div>
            ))}
          </div>
        </div>

        <div className={cn(landingStyles.panelAccent, "relative overflow-hidden p-0 rounded-3xl shadow-sm border-orange-500/25")}>
          <div className="flex items-center gap-2 border-b border-border/50 bg-muted/40 px-4 py-3">
            <div className="flex items-center gap-1.5 mr-2">
              <span className="h-2.5 w-2.5 rounded-full bg-red-400/80" />
              <span className="h-2.5 w-2.5 rounded-full bg-amber-400/80" />
              <span className="h-2.5 w-2.5 rounded-full bg-emerald-400/80" />
            </div>
            <Terminal className="h-3.5 w-3.5 text-orange-500" />
            <span className="text-xs font-medium text-muted-foreground font-mono">
              main.tf — live preview
            </span>
            <span className="ml-auto rounded-full border border-emerald-500/30 bg-emerald-500/10 px-2.5 py-0.5 text-[10px] font-semibold text-emerald-600 dark:text-emerald-400">
              ● validated
            </span>
          </div>
          <pre className={cn(landingStyles.codeBlock, "rounded-none border-0 h-[240px] sm:h-[300px] bg-zinc-950 p-4")}>
            <code className="block text-xs font-mono leading-relaxed whitespace-pre-wrap text-zinc-200">{HERO_CODE}</code>
          </pre>
        </div>
      </div>
    </section>
  );
}
