"use client";

import { ArrowRight, Github, Sparkles, Terminal } from "lucide-react";
import { useTheme } from "next-themes";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { landingStyles } from "./shared/landing-styles";
import { HERO_STATS } from "./landing-data";
import { cn } from "@/lib/utils";

interface LandingHeroProps {
  onGetStarted: () => void;
}

const HERO_CODE = `# Generated by AWS Infra Generator
terraform {
  required_version = ">= 1.5"
}

resource "aws_vpc" "main" {
  cidr_block = var.vpc_cidr
  tags       = local.common_tags
}`;

export function LandingHero({ onGetStarted }: LandingHeroProps) {
  const { resolvedTheme } = useTheme();
  const [mounted, setMounted] = useState(false);

  useEffect(() => setMounted(true), []);

  const logoSrc =
    mounted && resolvedTheme === "dark" ? "/AWS-Dark.svg" : "/AWS-Light.svg";

  return (
    <section className="relative overflow-hidden px-1 sm:px-0 pt-2 sm:pt-4">
      <div className={landingStyles.heroGlow} />

      <div className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr] lg:items-center lg:gap-8">
        <div className="space-y-4 sm:space-y-5 text-center lg:text-left">
          <div className="flex justify-center lg:justify-start">
            <span className={landingStyles.eyebrow}>
              <Sparkles className="h-3 w-3" />
              Platform Engineering Tool
            </span>
          </div>

          <div className="flex justify-center lg:justify-start">
            <div className="inline-flex items-center justify-center rounded-xl border border-orange-500/25 bg-card/80 p-3 shadow-sm backdrop-blur-sm">
              <img
                src={logoSrc}
                alt="AWS Logo"
                className="h-10 w-auto sm:h-12"
                suppressHydrationWarning
              />
            </div>
          </div>

          <h1 className="text-2xl sm:text-4xl lg:text-5xl font-bold tracking-tight leading-[1.15]">
            Design AWS infrastructure.
            <span className="block text-orange-600 dark:text-orange-400">
              Ship IaC in minutes.
            </span>
          </h1>

          <p className="text-xs sm:text-base text-muted-foreground max-w-xl mx-auto lg:mx-0 leading-relaxed">
            Select services, configure parameters, and generate production-ready
            Terraform or CloudFormation — with validation, diagrams, and cost
            estimates built in.
          </p>

          <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-center lg:justify-start gap-2 sm:gap-3">
            <Button
              size="lg"
              onClick={onGetStarted}
              className={cn("w-full sm:w-auto text-sm", landingStyles.ctaPrimary)}
              id="get-started"
            >
              Get Started
              <ArrowRight className="ml-1.5 h-4 w-4" />
            </Button>
            <a
              href="https://github.com/NotHarshhaa/aws-infra-generator"
              target="_blank"
              rel="noopener noreferrer"
              className="w-full sm:w-auto"
            >
              <Button variant="outline" size="lg" className="w-full sm:w-auto text-sm h-9 sm:h-10">
                <Github className="mr-1.5 h-4 w-4" />
                View on GitHub
              </Button>
            </a>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 sm:gap-3 max-w-xl mx-auto lg:mx-0">
            {HERO_STATS.map((stat) => (
              <div key={stat.label} className={landingStyles.statChip}>
                <span className={cn(landingStyles.statValue, "text-orange-600 dark:text-orange-400")}>
                  {stat.value}
                </span>
                <span className={landingStyles.statLabel}>{stat.label}</span>
              </div>
            ))}
          </div>
        </div>

        <div className={cn(landingStyles.panelAccent, "relative overflow-hidden p-0")}>
          <div className="flex items-center gap-2 border-b border-orange-500/15 px-3 py-2 sm:px-4">
            <Terminal className="h-3.5 w-3.5 text-orange-500" />
            <span className="text-[11px] sm:text-xs font-medium text-muted-foreground">
              main.tf — preview
            </span>
            <span className="ml-auto rounded-md border border-green-500/30 bg-green-500/10 px-1.5 py-0.5 text-[10px] font-medium text-green-700 dark:text-green-400">
              validated
            </span>
          </div>
          <pre className={cn(landingStyles.codeBlock, "rounded-none border-0 h-[220px] sm:h-[280px]")}>
            <code className="block p-3 sm:p-4 whitespace-pre-wrap">{HERO_CODE}</code>
          </pre>
        </div>
      </div>
    </section>
  );
}
