import { GeneratedFile } from '../types';

export function generateVariables(
  services: string[],
  config: Record<string, any>,
  environment: string,
  region: string,
  projectName: string
): GeneratedFile {
  const lines: string[] = [
    `# General Configuration`,
    `variable "aws_region" {`,
    `  description = "AWS region where resources will be deployed"`,
    `  type        = string`,
    `  default     = "${region}"`,
    `  validation {`,
    `    condition     = can(regex("^us-(east|west)-[1-2]$", var.aws_region)) || can(regex("^eu-(central|west)-[1-3]$", var.aws_region))`,
    `    error_message = "AWS region must be a valid commercial region."`,
    `  }`,
    `}`,
    ``,
    `variable "environment" {`,
    `  description = "Environment name (development, staging, production)"`,
    `  type        = string`,
    `  default     = "${environment}"`,
    `  validation {`,
    `    condition     = contains(["development", "staging", "production"], var.environment)`,
    `    error_message = "Environment must be one of: development, staging, production."`,
    `  }`,
    `}`,
    ``,
    `variable "project_name" {`,
    `  description = "Project name for resource naming"`,
    `  type        = string`,
    `  default     = "${projectName}"`,
    `  validation {`,
    `    condition     = can(regex("^[a-z0-9-]{3,16}$", var.project_name))`,
    `    error_message = "Project name must be 3-16 characters, lowercase, numbers and hyphens only."`,
    `  }`,
    `}`,
    ``,
    `# Cost and Ownership`,
    `variable "cost_center" {`,
    `  description = "Cost center for billing purposes"`,
    `  type        = string`,
    `  default     = "engineering"`,
    `}`,
    ``,
    `variable "owner_email" {`,
    `  description = "Email of the resource owner"`,
    `  type        = string`,
    `  default     = "team@example.com"`,
    `  validation {`,
    `    condition     = can(regex("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$", var.owner_email))`,
    `    error_message = "Owner email must be a valid email address."`,
    `  }`,
    `}`,
    ``,
    `# Security`,
    `variable "allowed_cidr_blocks" {`,
    `  description = "List of CIDR blocks allowed for SSH access"`,
    `  type        = list(string)`,
    `  default     = ["0.0.0.0/0"]`,
    `  validation {`,
    `    condition     = length(var.allowed_cidr_blocks) > 0`,
    `    error_message = "At least one CIDR block must be specified."`,
    `  }`,
    `}`,
    ``,
    `variable "ssh_key_pair_name" {`,
    `  description = "Name of the SSH key pair for EC2 instances"`,
    `  type        = string`,
    `  default     = ""`,
    `}`,
  ];

  if (services.includes("vpc")) {
    const vpcCfg = config.vpc?.config || {};
    lines.push(
      ``,
      `# VPC Configuration`,
      `variable "vpc_cidr" {`,
      `  description = "CIDR block for the VPC"`,
      `  type        = string`,
      `  default     = "${vpcCfg.cidr_block || "10.0.0.0/16"}"`,
      `  validation {`,
      `    condition     = can(regex("^([0-9]{1,3}\\.){3}[0-9]{1,3}/[0-9]{1,2}$", var.vpc_cidr))`,
      `    error_message = "VPC CIDR must be a valid CIDR notation."`,
      `  }`,
      `}`,
      ``,
      `variable "availability_zones" {`,
      `  description = "List of availability zones to use"`,
      `  type        = list(string)`,
      `  default     = ${JSON.stringify(vpcCfg.availability_zones || ["us-east-1a", "us-east-1b", "us-east-1c"])}`,
      `  validation {`,
      `    condition     = length(var.availability_zones) >= 2`,
      `    error_message = "At least 2 availability zones must be specified for high availability."`,
      `  }`,
      `}`,
      ``,
      `variable "enable_nat_gateway" {`,
      `  description = "Enable NAT gateway for private subnets"`,
      `  type        = bool`,
      `  default     = ${vpcCfg.enable_nat !== false}`,
      `}`,
      ``,
      `variable "enable_vpc_flow_logs" {`,
      `  description = "Enable VPC Flow Logs for network monitoring"`,
      `  type        = bool`,
      `  default     = true`,
      `}`
    );
  }

  if (services.includes("ec2")) {
    const ec2Cfg = config.ec2?.config || {};
    lines.push(
      ``,
      `# EC2 Configuration`,
      `variable "instance_type" {`,
      `  description = "EC2 instance type"`,
      `  type        = string`,
      `  default     = "${ec2Cfg.instance_type || "t3.medium"}"`,
      `  validation {`,
      `    condition     = contains(["t3.micro", "t3.small", "t3.medium", "t3.large", "m5.large", "m5.xlarge"], var.instance_type)`,
      `    error_message = "Instance type must be a supported type."`,
      `  }`,
      `}`,
      ``,
      `variable "instance_count" {`,
      `  description = "Number of EC2 instances to deploy"`,
      `  type        = number`,
      `  default     = ${ec2Cfg.instance_count || 2}`,
      `  validation {`,
      `    condition     = var.instance_count >= 1 && var.instance_count <= 10`,
      `    error_message = "Instance count must be between 1 and 10."`,
      `  }`,
      `}`,
      ``,
      `variable "root_volume_size" {`,
      `  description = "Size of the root volume in GB"`,
      `  type        = number`,
      `  default     = ${ec2Cfg.root_volume_size || 50}`,
      `  validation {`,
      `    condition     = var.root_volume_size >= 20 && var.root_volume_size <= 1000`,
      `    error_message = "Root volume size must be between 20 and 1000 GB."`,
      `  }`,
      `}`,
      ``,
      `variable "enable_monitoring" {`,
      `  description = "Enable detailed monitoring for EC2 instances"`,
      `  type        = bool`,
      `  default     = true`,
      `}`,
      ``,
      `variable "ami_id" {`,
      `  description = "Custom AMI ID (overrides default AMI selection)"`,
      `  type        = string`,
      `  default     = ""`,
      `}`
    );
  }

  if (services.includes("rds")) {
    const rdsCfg = config.rds?.config || {};
    lines.push(
      ``,
      `# RDS Configuration`,
      `variable "db_engine" {`,
      `  description = "Database engine"`,
      `  type        = string`,
      `  default     = "${rdsCfg.engine || "postgres"}"`,
      `  validation {`,
      `    condition     = contains(["postgres", "mysql"], var.db_engine)`,
      `    error_message = "Database engine must be postgres or mysql."`,
      `  }`,
      `}`,
      ``,
      `variable "db_instance_class" {`,
      `  description = "RDS instance class"`,
      `  type        = string`,
      `  default     = "${rdsCfg.instance_class || "db.t3.medium"}"`,
      `}`,
      ``,
      `variable "db_allocated_storage" {`,
      `  description = "RDS allocated storage in GB"`,
      `  type        = number`,
      `  default     = ${rdsCfg.allocated_storage || 100}`,
      `  validation {`,
      `    condition     = var.db_allocated_storage >= 20 && var.db_allocated_storage <= 65536`,
      `    error_message = "RDS storage must be between 20 and 65536 GB."`,
      `  }`,
      `}`,
      ``,
      `variable "db_name" {`,
      `  description = "Database name"`,
      `  type        = string`,
      `  default     = "${rdsCfg.database_name || "appdb"}"`,
      `  validation {`,
      `    condition     = can(regex("^[a-zA-Z][a-zA-Z0-9_]*$", var.db_name))`,
      `    error_message = "Database name must start with a letter and contain only letters, numbers, and underscores."`,
      `  }`,
      `}`,
      ``,
      `variable "db_username" {`,
      `  description = "Database master username"`,
      `  type        = string`,
      `  default     = "${rdsCfg.username || "appadmin"}"`,
      `  sensitive   = true`,
      `}`,
      ``,
      `variable "db_password" {`,
      `  description = "Database master password"`,
      `  type        = string`,
      `  default     = ""`,
      `  sensitive   = true`,
      `  validation {`,
      `    condition     = length(var.db_password) >= 8`,
      `    error_message = "Database password must be at least 8 characters long."`,
      `  }`,
      `}`,
      ``,
      `variable "enable_db_backup_retention" {`,
      `  description = "Enable automated backups"`,
      `  type        = bool`,
      `  default     = true`,
      `}`,
      ``,
      `variable "db_backup_retention_period" {`,
      `  description = "Backup retention period in days"`,
      `  type        = number`,
      `  default     = ${rdsCfg.backup_retention || 7}`,
      `  validation {`,
      `    condition     = var.db_backup_retention_period >= 1 && var.db_backup_retention_period <= 35`,
      `    error_message = "Backup retention period must be between 1 and 35 days."`,
      `  }`,
      `}`,
      ``,
      `variable "enable_multi_az" {`,
      `  description = "Enable Multi-AZ deployment for high availability"`,
      `  type        = bool`,
      `  default     = ${environment === "production"}`,
      `}`
    );
  }

  if (services.includes("s3")) {
    const s3Cfg = config.s3?.config || {};
    lines.push(
      ``,
      `# S3 Configuration`,
      `variable "s3_bucket_name_prefix" {`,
      `  description = "Prefix for S3 bucket name"`,
      `  type        = string`,
      `  default     = "${s3Cfg.bucket_name || "app-data"}"`,
      `}`,
      ``,
      `variable "enable_s3_versioning" {`,
      `  description = "Enable S3 bucket versioning"`,
      `  type        = bool`,
      `  default     = ${s3Cfg.versioning !== false}`,
      `}`,
      ``,
      `variable "s3_lifecycle_transition_days" {`,
      `  description = "Days after which to transition to IA storage"`,
      `  type        = number`,
      `  default     = ${s3Cfg.lifecycle_days || 30}`,
      `  validation {`,
      `    condition     = var.s3_lifecycle_transition_days >= 30`,
      `    error_message = "S3 lifecycle transition must be at least 30 days."`,
      `  }`,
      `}`,
      ``,
      `variable "enable_s3_encryption" {`,
      `  description = "Enable S3 server-side encryption"`,
      `  type        = bool`,
      `  default     = true`,
      `}`,
      ``,
      `variable "s3_encryption_algorithm" {`,
      `  description = "S3 encryption algorithm"`,
      `  type        = string`,
      `  default     = "${s3Cfg.encryption || "AES256"}"`,
      `  validation {`,
      `    condition     = contains(["AES256", "aws:kms"], var.s3_encryption_algorithm)`,
      `    error_message = "Encryption algorithm must be AES256 or aws:kms."`,
      `  }`,
      `}`
    );
  }

  const content = lines.join('\n') + '\n';
  return {
    name: "variables.tf",
    path: `${projectName}/variables.tf`,
    content,
    language: "hcl",
  };
}
