import { ServiceConfig, GeneratedFile } from "../../types";

export class CDKGenerator {
  public generate(
    services: string[],
    config: ServiceConfig,
    environment: string,
    region: string,
    projectName: string
  ): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    // Clean project name for class names (PascalCase)
    const cleanProjectName = projectName
      .replace(/[^a-zA-Z0-9]/g, " ")
      .split(" ")
      .filter(Boolean)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join("");
    const stackClassName = `${cleanProjectName}Stack`;

    // 1. bin/app.ts
    const appTsContent = `#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import { ${stackClassName} } from '../lib/infra-stack';

const app = new cdk.App();

new ${stackClassName}(app, '${projectName}-${environment}', {
  env: {
    account: process.env.CDK_DEFAULT_ACCOUNT || process.env.AWS_ACCOUNT_ID,
    region: '${region}',
  },
  description: 'Infrastructure stack for ${projectName} (${environment}) generated by AWS Infra Generator',
});
`;
    files.push({
      name: "bin/app.ts",
      path: `${projectName}/bin/app.ts`,
      content: appTsContent,
      language: "typescript",
    });

    // 2. lib/infra-stack.ts
    const stackTsContent = this.generateStackClass(
      stackClassName,
      services,
      config,
      environment,
      region,
      projectName
    );
    files.push({
      name: "lib/infra-stack.ts",
      path: `${projectName}/lib/infra-stack.ts`,
      content: stackTsContent,
      language: "typescript",
    });

    // 3. cdk.json
    const cdkJsonContent = JSON.stringify(
      {
        app: "npx ts-node --prefer-ts-exts bin/app.ts",
        watch: {
          include: ["**"],
          exclude: [
            "README.md",
            "cdk.out",
            "*.d.ts",
            "*.js",
            "node_modules",
          ],
        },
        context: {
          "@aws-cdk/aws-lambda:recognizeLayerVersion": true,
          "@aws-cdk/core:checkSecretUsage": true,
          "@aws-cdk/core:target-partitions": ["aws", "aws-cn"],
          "@aws-cdk-lib/aws-s3:grantWriteWithoutAcl": true,
          "@aws-cdk/aws-ecs-patterns:removeDefaultDesiredCount": true,
          "@aws-cdk/aws-rds:databaseProxyUniqueAttributeManagement": true,
          "@aws-cdk/aws-iam:minimizePolicies": true,
        },
      },
      null,
      2
    );
    files.push({
      name: "cdk.json",
      path: `${projectName}/cdk.json`,
      content: cdkJsonContent,
      language: "json",
    });

    // 4. package.json
    const packageJsonContent = JSON.stringify(
      {
        name: projectName,
        version: "0.1.0",
        bin: {
          [projectName]: "bin/app.js",
        },
        scripts: {
          build: "tsc",
          watch: "tsc -w",
          test: "jest",
          cdk: "cdk",
          synth: "cdk synth",
          deploy: "cdk deploy",
          diff: "cdk diff",
        },
        devDependencies: {
          "@types/node": "^20.11.0",
          "aws-cdk": "^2.130.0",
          "ts-node": "^10.9.2",
          typescript: "^5.3.3",
        },
        dependencies: {
          "aws-cdk-lib": "^2.130.0",
          constructs: "^10.3.0",
          "source-map-support": "^0.5.21",
        },
      },
      null,
      2
    );
    files.push({
      name: "package.json",
      path: `${projectName}/package.json`,
      content: packageJsonContent,
      language: "json",
    });

    // 5. tsconfig.json
    const tsconfigJsonContent = JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "commonjs",
          lib: ["es2022"],
          declaration: true,
          strict: true,
          noImplicitAny: true,
          strictNullChecks: true,
          noImplicitThis: true,
          alwaysStrict: true,
          noUnusedLocals: false,
          noUnusedParameters: false,
          exactOptionalPropertyTypes: false,
          noImplicitReturns: true,
          noFallthroughCasesInSwitch: false,
          inlineSourceMap: true,
          inlineSources: true,
          experimentalDecorators: true,
          strictPropertyInitialization: false,
          typeRoots: ["./node_modules/@types"],
        },
        exclude: ["node_modules", "cdk.out"],
      },
      null,
      2
    );
    files.push({
      name: "tsconfig.json",
      path: `${projectName}/tsconfig.json`,
      content: tsconfigJsonContent,
      language: "json",
    });

    return files;
  }

  private generateStackClass(
    className: string,
    services: string[],
    config: ServiceConfig,
    environment: string,
    region: string,
    projectName: string
  ): string {
    const imports: Set<string> = new Set([
      "import * as cdk from 'aws-cdk-lib';",
      "import { Construct } from 'constructs';",
    ]);

    const codeBlocks: string[] = [];

    // Helper to get service config value
    const getCfg = (serviceId: string, key: string, fallback: any) =>
      config[serviceId]?.config?.[key] ?? fallback;

    // VPC
    if (services.includes("vpc")) {
      imports.add("import * as ec2 from 'aws-cdk-lib/aws-ec2';");
      const cidr = getCfg("vpc", "cidr_block", "10.0.0.0/16");
      const enableNat = getCfg("vpc", "enable_nat", false);
      const publicSubnets = parseInt(String(getCfg("vpc", "public_subnets", "2")), 10);
      const privateSubnets = parseInt(String(getCfg("vpc", "private_subnets", "2")), 10);

      codeBlocks.push(`
    // Virtual Private Cloud (VPC)
    const vpc = new ec2.Vpc(this, 'Vpc', {
      vpcName: '${projectName}-${environment}-vpc',
      ipAddresses: ec2.IpAddresses.cidr('${cidr}'),
      maxAzs: Math.max(${publicSubnets}, ${privateSubnets}),
      natGateways: ${enableNat ? 1 : 0},
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: 'Public',
          subnetType: ec2.SubnetType.PUBLIC,
        },
        ${
          privateSubnets > 0
            ? `{
          cidrMask: 24,
          name: 'Private',
          subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS,
        }`
            : ""
        }
      ],
    });`);
    }

    // EC2
    if (services.includes("ec2")) {
      imports.add("import * as ec2 from 'aws-cdk-lib/aws-ec2';");
      const instanceType = getCfg("ec2", "instance_type", "t3.micro");
      const instanceCount = Number(getCfg("ec2", "instance_count", 1));
      const rootVolumeSize = Number(getCfg("ec2", "root_volume_size", 20));

      codeBlocks.push(`
    // Security Group for EC2
    const ec2SecurityGroup = new ec2.SecurityGroup(this, 'Ec2SecurityGroup', {
      vpc: ${services.includes("vpc") ? "vpc" : "ec2.Vpc.fromLookup(this, 'DefaultVpc', { isDefault: true })"},
      description: 'Security group for EC2 instances',
      allowAllOutbound: true,
    });
    ec2SecurityGroup.addIngressRule(ec2.Peer.anyIpv4(), ec2.Port.tcp(22), 'Allow SSH access');
    ec2SecurityGroup.addIngressRule(ec2.Peer.anyIpv4(), ec2.Port.tcp(80), 'Allow HTTP access');

    // EC2 Instances
    for (let i = 0; i < ${instanceCount}; i++) {
      new ec2.Instance(this, \`Ec2Instance\${i + 1}\`, {
        instanceName: \`${projectName}-${environment}-ec2-\${i + 1}\`,
        vpc: ${services.includes("vpc") ? "vpc" : "ec2.Vpc.fromLookup(this, 'DefaultVpc', { isDefault: true })"},
        instanceType: new ec2.InstanceType('${instanceType}'),
        machineImage: ec2.MachineImage.latestAmazonLinux2023(),
        securityGroup: ec2SecurityGroup,
        blockDevices: [
          {
            deviceName: '/dev/xvda',
            volume: ec2.BlockDeviceVolume.ebs(${rootVolumeSize}, {
              volumeType: ec2.EbsDeviceVolumeType.GP3,
              encrypted: true,
            }),
          },
        ],
      });
    }`);
    }

    // S3
    if (services.includes("s3")) {
      imports.add("import * as s3 from 'aws-cdk-lib/aws-s3';");
      const bucketSuffix = getCfg("s3", "bucket_name", "data");
      const versioning = getCfg("s3", "versioning", true);
      const blockPublic = getCfg("s3", "block_public_access", true);

      codeBlocks.push(`
    // S3 Bucket
    const bucket = new s3.Bucket(this, 'StorageBucket', {
      bucketName: \`${projectName}-${environment}-${bucketSuffix}-\${cdk.Aws.ACCOUNT_ID}\`,
      versioned: ${versioning},
      encryption: s3.BucketEncryption.S3_MANAGED,
      blockPublicAccess: ${
        blockPublic
          ? "s3.BlockPublicAccess.BLOCK_ALL"
          : "s3.BlockPublicAccess.BLOCK_ACLS"
      },
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: ${environment !== "production"},
    });`);
    }

    // RDS
    if (services.includes("rds")) {
      imports.add("import * as rds from 'aws-cdk-lib/aws-rds';");
      imports.add("import * as ec2 from 'aws-cdk-lib/aws-ec2';");
      const engine = getCfg("rds", "engine", "postgres");
      const instanceClass = getCfg("rds", "instance_class", "db.t3.micro");
      const allocatedStorage = Number(getCfg("rds", "allocated_storage", 20));
      const multiAz = getCfg("rds", "multi_az", false);

      const rdsEngineSnippet =
        engine === "postgres"
          ? "rds.DatabaseInstanceEngine.postgres({ version: rds.PostgresEngineVersion.VER_16_1 })"
          : engine === "mysql"
          ? "rds.DatabaseInstanceEngine.mysql({ version: rds.MysqlEngineVersion.VER_8_0 })"
          : "rds.DatabaseInstanceEngine.postgres({ version: rds.PostgresEngineVersion.VER_16_1 })";

      codeBlocks.push(`
    // RDS Database Instance
    const dbInstance = new rds.DatabaseInstance(this, 'RdsDatabase', {
      engine: ${rdsEngineSnippet},
      instanceType: new ec2.InstanceType('${String(instanceClass).replace("db.", "")}'),
      vpc: ${services.includes("vpc") ? "vpc" : "ec2.Vpc.fromLookup(this, 'DefaultVpc', { isDefault: true })"},
      allocatedStorage: ${allocatedStorage},
      multiAz: ${multiAz},
      databaseName: '${projectName.replace(/[^a-zA-Z0-9]/g, "")}_db',
      credentials: rds.Credentials.fromGeneratedSecret('admin'),
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });`);
    }

    // DynamoDB
    if (services.includes("dynamodb")) {
      imports.add("import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';");
      const tableName = getCfg("dynamodb", "table_name", "table");

      codeBlocks.push(`
    // DynamoDB Table
    const dynamoTable = new dynamodb.Table(this, 'DynamoDbTable', {
      tableName: \`${projectName}-${environment}-${tableName}\`,
      partitionKey: { name: 'id', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });`);
    }

    // Lambda
    if (services.includes("lambda")) {
      imports.add("import * as lambda from 'aws-cdk-lib/aws-lambda';");
      const memory = Number(getCfg("lambda", "memory_size", 128));

      codeBlocks.push(`
    // Lambda Function
    const lambdaFunction = new lambda.Function(this, 'ApiFunction', {
      functionName: \`${projectName}-${environment}-api-handler\`,
      runtime: lambda.Runtime.NODEJS_20_X,
      handler: 'index.handler',
      code: lambda.Code.fromInline(\`
        exports.handler = async (event) => {
          return {
            statusCode: 200,
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ message: 'Hello from ${projectName}!' }),
          };
        };
      \`),
      memorySize: ${memory},
      timeout: cdk.Duration.seconds(10),
    });`);
    }

    // ALB
    if (services.includes("alb")) {
      imports.add("import * as elbv2 from 'aws-cdk-lib/aws-elasticloadbalancingv2';");
      codeBlocks.push(`
    // Application Load Balancer
    const alb = new elbv2.ApplicationLoadBalancer(this, 'AppLoadBalancer', {
      vpc: ${services.includes("vpc") ? "vpc" : "ec2.Vpc.fromLookup(this, 'DefaultVpc', { isDefault: true })"},
      internetFacing: true,
      loadBalancerName: \`${projectName}-${environment}-alb\`,
    });`);
    }

    // API Gateway
    if (services.includes("api-gateway")) {
      imports.add("import * as apigateway from 'aws-cdk-lib/aws-apigateway';");
      codeBlocks.push(`
    // API Gateway REST API
    const api = new apigateway.RestApi(this, 'RestApi', {
      restApiName: \`${projectName}-${environment}-api\`,
      description: 'API Gateway for ${projectName}',
      deployOptions: {
        stageName: '${environment}',
      },
    });
    ${
      services.includes("lambda")
        ? `api.root.addMethod('GET', new apigateway.LambdaIntegration(lambdaFunction));`
        : ""
    }`);
    }

    // CloudFront
    if (services.includes("cloudfront")) {
      imports.add("import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';");
      imports.add("import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';");
      codeBlocks.push(`
    // CloudFront Distribution
    ${
      services.includes("s3")
        ? `const distribution = new cloudfront.Distribution(this, 'CdnDistribution', {
      defaultBehavior: {
        origin: new origins.S3Origin(bucket),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
      },
      comment: \`CDN Distribution for ${projectName} (${environment})\`,
    });`
        : `// CloudFront setup (requires origin)`
    }`);
    }

    // Cognito
    if (services.includes("cognito")) {
      imports.add("import * as cognito from 'aws-cdk-lib/aws-cognito';");
      codeBlocks.push(`
    // Cognito User Pool
    const userPool = new cognito.UserPool(this, 'UserPool', {
      userPoolName: \`${projectName}-${environment}-user-pool\`,
      selfSignUpEnabled: true,
      signInAliases: { email: true },
      autoVerify: { email: true },
      standardAttributes: {
        email: { required: true, mutable: true },
      },
    });

    const userPoolClient = new cognito.UserPoolClient(this, 'UserPoolClient', {
      userPool,
      userPoolClientName: \`${projectName}-${environment}-client\`,
      generateSecret: false,
    });`);
    }

    // ElastiCache
    if (services.includes("elasticache")) {
      imports.add("import * as elasticache from 'aws-cdk-lib/aws-elasticache';");
      codeBlocks.push(`
    // ElastiCache Redis Cluster
    const redisCluster = new elasticache.CfnCacheCluster(this, 'RedisCacheCluster', {
      cacheNodeType: 'cache.t3.micro',
      engine: 'redis',
      numCacheNodes: 1,
      clusterName: \`${projectName}-${environment}-redis\`,
    });`);
    }

    // Secrets Manager
    if (services.includes("secrets-manager")) {
      imports.add("import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';");
      codeBlocks.push(`
    // Secrets Manager Secret
    const appSecret = new secretsmanager.Secret(this, 'AppSecret', {
      secretName: \`${projectName}/${environment}/config\`,
      description: 'Application secrets for ${projectName}',
    });`);
    }

    // EventBridge
    if (services.includes("eventbridge")) {
      imports.add("import * as events from 'aws-cdk-lib/aws-events';");
      codeBlocks.push(`
    // EventBridge Event Bus
    const eventBus = new events.EventBus(this, 'AppEventBus', {
      eventBusName: \`${projectName}-${environment}-bus\`,
    });`);
    }

    const importsArray = Array.from(imports).sort().join("\n");
    const codeBody = codeBlocks.join("\n");

    return `${importsArray}

export class ${className} extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
${codeBody}

    // Stack Outputs
    new cdk.CfnOutput(this, 'ProjectName', { value: '${projectName}' });
    new cdk.CfnOutput(this, 'Environment', { value: '${environment}' });
  }
}
`;
  }
}
